bad_words = [
    "fuck", "bastard", "shit", "damn", "asshole", "bitch", "cock", "pussy", "cunt",
    "dick", "motherfucker", "ass", "slut", "whore", "twat", "arse", "bollocks",
    "wanker", "fucker", "crap", "arsehole", "prick", "bugger", "screw", "douchebag",
    "arsewipe", "bellend", "wank", "sod", "tosser", "douche", "shithead", "bullshit",
    "dickhead", "knobhead", "arsehat", "shitface", "jackass", "fuckwit", "dickwad",
    "arseface", "asshat", "twatsicle", "fuckface", "piss", "git", "schmuck", "fucktard",
    "fuckery", "cunty", "assclown", "shitbag", "asswipe", "scumbag", "douche canoe",
    "dickbag", "shitforbrains", "cockwomble", "cockwaffle", "fucknugget", "pissflap",
    "cockgobbler", "shitgibbon", "assbiscuit", "dickweed", "cockwomble", "clusterfuck",
    "wankstain", "shitstain", "cockjuggling thundercunt", "arsebiscuit", "twatwaffle",
    "crapweasel", "shitnugget", "douchecanoe", "fuckknuckle", "cockjockey", "cocksocket",
    "arseclown", "shithead", "fuckbucket", "dickface", "twatlips", "douchewaffle",
    "cockburger", "shitbrick", "cuntflap", "shitstick", "arsebadger", "dickpickle",
    "cockholster", "twathammer", "fuckstick", "arsewipe", "shitwad", "twatwaffle",
    "cockwomble", "asshats", "assmunch", "cumdumpster", "douchenozzle", "fartknocker",
    "fucknugget", "pisshead", "shitbreath", "cocknugget", "turdbrain", "asslicker",
    "boogerface", "dicknose", "pisswhistle", "twatwaffle", "sackofshit", "shitbag",
    "cumbubble", "fartface", "pissface", "assbandit", "buttmonkey", "dickbreath",
    "pissbucket", "shitbucket", "fartknocker", "cumstain", "fartknocker", "dickweasel",
    "pissdrinker", "snotface", "turdmonkey", "vomitface", "assface", "asswipe",
    "crapface", "dickweed", "pissflap", "shitforbrains", "turdferguson", "twatwaffle",
    "fartbreath", "snotnose", "cockroach", "fartnugget", "dicklips", "shitlips",
    "assbiscuit", "douchetard", "shitknuckle", "assburgers", "fartmonger", "dicklicker",
    "shitlicker", "fartlicker", "dickmuncher", "fartmuncher", "doucheburger", "shitburger",
    "turdherder", "shitwizard", "turdwrangler", "fartknocker", "shitgoblin", "douchecanoe",
    "fartcannon", "shitcannon", "shitnugget", "dicknugget", "fartnugget", "dickhead",
    "asshead", "shithead", "turdhead", "fartface", "shitface", "dickface", "fartbreath",
    "shitbreath", "dickbreath", "shitstick", "turdstick", "dickstick", "fuckstick",
    "douchestick", "fuckhole", "dickhole", "asshole", "shithole", "turdhole", "fartknuckle",
    "shitknuckle", "dickknuckle", "fuckknuckle", "twatknuckle", "fartbiscuit", "shitbiscuit",
    "dickbiscuit", "douchewaffle", "fartwaffle", "shitwaffle", "dickwaffle", "fuckwaffle",
    "twatwaffle", "fartmuffin", "shitmuffin", "dickmuffin", "douchenugget", "fartnugget",
    "shitturd", "dickturd", "fuckturd", "twatturd", "shitpickle", "dickpickle", "fuckpickle",
    "fartpickle", "shitsniffer", "dicksniffer", "fucksucker", "shitsucker", "dicksucker",
    "turdswallower", "fartswallower", "assmaggot", "shitmaggot", "dickmaggot", "fuckmaggot",
    "fartmaggot", "douchebag", "shitbag", "dickbag", "fuckbag", "fartbag", "assbag",
    "turdnugget", "fucknugget", "shitnugget", "dicknugget", "fartnugget", "shitbox",
    "dickbox", "fuckbox", "fartbox", "assbox", "turdbox", "cockblock", "shitblock",
    "dickblock", "fuckblock", "fartblock", "assblock", "turdmonkey", "fuckmonkey",
    "shitmonkey", "dickmonkey", "fartmonkey", "assmonkey", "turdface", "fuckface",
    "shitface", "dickface", "fartface", "assface", "turdhead", "fuckhead", "shithead",
    "dickhead", "farthead", "asshead", "turdbrain", "fuckbrain", "shitbrain", "dickbrain",
    "fartbrain", "assbrain", "turdflinger", "fuckflinger", "shitflinger", "dickflinger",
    "fartflinger", "assflinger", "turdherder", "fuckherder", "shitherder", "dickherder",
    "fartherder", "assherder", "turdwaffle", "fuckwaffle", "shitwaffle", "dickwaffle",
    "fartwaffle", "asswaffle", "turdnugget", "fucknugget", "shitnugget", "dicknugget",
    "fartnugget", "assnugget", "turdrocket", "fuckrocket", "shitrocket", "dickrocket",
    "farrocket", "assrocket", "turdsmack", "fucksmack", "shitsmack", "dicksmack",
    "fartsmack", "asssmack", "turdstain", "fuckstain", "shitstain", "dickstain",
    "fartstain", "assstain", "turdwagon", "fuckwagon", "shitwagon", "dickwagon",
    "fartwagon", "asswagon", "turdwad", "fuckwad", "shitwad", "dickwad", "fartwad",
    "asswad", "turdweasel", "fuckweasel", "shitweasel", "dickweasel", "fartweasel",
    "assweasel", "turdwhistle", "fuckwhistle", "shitwhistle", "dickwhistle",
    "fartwhistle", "asswhistle", "twat", "bastard", "bollocks", "sod", "git", "tosser",
    "screw", "bugger", "bellend", "wank", "tosser", "pissflaps", "cockwomble", "clunge",
    "flange", "knob", "minge", "muff", "quim", "twunt", "gash", "spunk", "jizz", "cum",
    "taint", "rimjob", "fanny", "knobend", "fud", "skank", "skankhole", "fuckwit", "thundercunt",
    "gutterwhore", "cumdumpster", "shitheel", "spermburger", "titwank", "assjacket", "fap",
    "dickcheese", "fucknoodle", "shitehawk", "slag", "wankstain", "bint", "flaps", "fuckface",
    "shitgoblin", "dickwarden", "cuntnugget", "cockgobbler", "shart", "dingleberry",
    "fucktrumpet", "turdferret", "asspuppet", "shitbeard", "assmaggot", "fucktrophies",
    "arseclown", "dickfuck", "shitbiscuits", "fuckweasel", "shitsquid", "fartnado",
    "shitstorm", "pisswizard", "cumsock", "fuckmuppet", "assmaster", "cumbucket",
    "fuckweasel", "shitsquid", "fartnado", "shitstorm", "pisswizard", "cumsock",
    "fuckmuppet", "assmaster", "cumbucket", "dickmonger", "cumguzzler", "asscandle",
    "fudgepacker", "fuckbucket", "cumdump", "cockgoblin", "cuntmuffin", "asspirate",
    "cuntbiscuit", "fucktrumpet", "shitgoblin", "dickwarden", "cuntnugget", "cockgobbler",
    "shart", "dingleberry", "fucktrumpet", "turdferret", "asspuppet", "shitbeard",
    "assmaggot", "fucktrophies", "arseclown", "dickfuck", "shitbiscuits", "fuckweasel",
    "shitsquid", "fartnado", "shitstorm", "pisswizard", "cumsock", "fuckmuppet", "assmaster",
    "cumbucket", "dickmonger", "cumguzzler", "asscandle", "fudgepacker", "fuckbucket",
    "cumdump", "cockgoblin", "cuntmuffin", "asspirate", "cuntbiscuit", "fucktrumpet",
    "shitgoblin", "dickwarden", "cuntnugget", "cockgobbler", "shart", "dingleberry",
    "fucktrumpet", "turdferret", "asspuppet", "shitbeard", "assmaggot", "fucktrophies",
    "arseclown", "dickfuck", "shitbiscuits", "fuckweasel", "shitsquid", "fartnado",
    "shitstorm", "pisswizard", "cumsock", "fuckmuppet", "assmaster", "cumbucket",
    "dickmonger", "cumguzzler", "asscandle", "fudgepacker", "fuckbucket", "cumdump",
    "cockgoblin", "cuntmuffin", "asspirate", "cuntbiscuit", "fucktrumpet", "shitgoblin",
    "dickwarden", "cuntnugget", "cockgobbler", "shart", "dingleberry", "fucktrumpet",
    "turdferret", "asspuppet", "shitbeard", "assmaggot", "fucktrophies", "arseclown",
    "dickfuck", "shitbiscuits", "fuckweasel", "shitsquid", "fartnado", "shitstorm",
    "pisswizard", "cumsock", "fuckmuppet", "assmaster", "cumbucket", "dickmonger",
    "cumguzzler", "asscandle", "fudgepacker", "fuckbucket", "cumdump", "cockgoblin",
    "cuntmuffin", "asspirate", "cuntbiscuit", "fucktrumpet"]